//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

export * from './shared';
export * from './clients/AuthClient';
export * from './clients/GoodsClient';
export * from './clients/OrdersClient';
export * from './clients/UsersClient';
export * from './models/CreateGoodRequest';
export * from './models/CreateOrderItemRequest';
export * from './models/CreateOrderRequest';
export * from './models/CreateUserRequest';
export * from './models/CreateUserRequestRole';
export * from './models/ErrorResponse';
export * from './models/Good';
export * from './models/LoginRequest';
export * from './models/LoginResponse';
export * from './models/Order';
export * from './models/OrderItem';
export * from './models/OrderStatus';
export * from './models/UpdateGoodRequest';
export * from './models/UpdateOrderRequest';
export * from './models/UpdateUserRequest';
export * from './models/UpdateUserRequestRole';
export * from './models/User';
export * from './models/UserRole';