//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

import { CreateUserRequestRole } from './CreateUserRequestRole';

export interface CreateUserRequest {
    username: string;
    password: string;
    email: string;
    role: CreateUserRequestRole;

    [key: string]: any;
}